### PR TITLE
ILTermini 7

### PR DESCRIPTION
**Pull request by valentinamignosa**
encoding text division, cleaning up the autogenerated text and checking the edition

### CODE REVIEW

**Review by simonastoyanova — CHANGES_REQUESTED** [review]
@valentinamignosa ISic0227, line 4, the number XI is outside the num element; same with XII in line 4 of ISic0228; same with XXX in line 2 of ISic0230

**Comment by JonPrag** [comment]
Took a quick look; nothing substantive beyond what @simonastoyanova noted, but two truly tiny questions: 
1. are we happy to continue tagging interpuncts as `<g type="interpunct">` on the assumption that we're just going to globally replace these in due course, provided we're consistent for now? [seems simplest?]. 
2. @simonastoyanova do you have a view on `<lb break="no" n="2">` vs `<lb n="2" break ="no">` I must confess I far prefer the second, for all that it presumably makes zero difference on the processing... (it's also cleaner and quicker to read visually).

**Comment by simonastoyanova** [comment]
@JonPrag 
1. I'm hoping to address the glyph question next week, after the EpiDoc 9.2 release, so we can make the change global. It will be easier to identify the `g`s we need to change if they are tagged in a relatively consistent, if not ideal, way. 
2. I also prefer the second, as it looks neater to me, but it doesn't change anything. Can tweak it globally.

**Comment by valentinamignosa** [comment]
thanks! about the `<g type="interpunct">` for now I'm adding the interpunct anyway because it wasn't present in the imported text (EDR doesn't report them). Maybe it is better to modify it when we have made a decision?

About the element `<lb n="2" break ="no">`also in this case it's better to replace them globally because of course there are many of them...

**Pull request merged**
