### PR TITLE
Lipari Files

### PR DESCRIPTION
**Pull request by AlexAAntoniou**

### CODE REVIEW

**Comment by AlexAAntoniou** [comment]
Hi @JonPrag. Something strange seems to be going on with the dts file. When I first created this pull-request last week, there was no dts file here, but then the bot 'updated the collection' multiple times which seems to have added a dts change to the PR. The only way I've been able to not let there be a conflict with the dts file is to manually download the dts file straight from the Master, and replace the one in my local fork (and then push the changes). Not sure why this has started – is anyone else struggling with a similar issue when they have an open PR?

**Comment by AlexAAntoniou** [comment]
Yep – last night's 'update collection' now conflicts again with the PR. Let me know when you want to resolve the PR and I'll update the dts file from the master.

**Comment by JonPrag** [comment]
Thanks, yes, it feels like there should be a way to exclude the dts file, but I'm not sure what it would be and why it gets added to the PR, but this sounds like a workaround, so I'll let you know as soon as I'm ready to resolve.
j

**Review by JonPrag — APPROVED** [review]
@AlexAAntoniou many thanks as always. Sorry for delay. Have now reviewed, a few tweaks to the ones on two faces or similar, but otherwise all good. Let me know when you've had a chance to replace the dts collection file, and that should remove the conflict and I'll merge the PR.

**Comment by AlexAAntoniou** [comment]
@JonPrag just replaced the dts file, so hopefully you'll be able to merge. I've been caught up with exams and conferences the last few weeks (and I'm on holiday next week), but will return to the Lipari files (or anything else you might need) on my return.

**Comment by JonPrag** [comment]
ta!

**Pull request merged**
