### PR TITLE
langUsage

### PR DESCRIPTION
**Pull request by simonastoyanova**
fixed list of languages where there was extra whitespace

### CODE REVIEW

**Review by JonPrag — APPROVED** [review]
embarrassing number of places where I've not deleted the bits from a pasted text after encoding... sigh...

**Review by JonPrag — CHANGES_REQUESTED** [review]
This commit on the language element however seems to be introducing a lot of extra line-breaks that weren't there before?

**Comment by JonPrag** [comment]
i.e. @simonastoyanova  the schematron check looks good, but I'm not sure the langusage correction does things we want?

**Comment by simonastoyanova** [comment]
I don't see the extra line breaks here... I can try the Oxygen Indent on those bits of they still look weird.

**Comment by simonastoyanova** [comment]
Done.

**Review by JonPrag — APPROVED** [review]

**Pull request merged**
